import steam from "../../assets/images/Home/steam.png";
import godWar from "../../assets/images/Home/god_war.png"
import farming from "../../assets/images/Home/farming.png";
import roblox from "../../assets/images/Home/roblox.png";
import xbox from "../../assets/images/Home/xbox.png";
import clientOne from "../../assets/images/Home/client.svg";
import clientTwo from "../../assets/images/Home/clientTwo.svg";

const giftCardData = [
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: steam,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "STEAM Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
];

const bestsellingCardData = [
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
];

const upcomingCardData = [
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
  {
    bgImg: farming,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "Farming Simulator 25 (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Giants Software",
    price: "8.00€",
    discountPrice: "4.00€",
  },
  {
    bgImg: godWar,
    rating: "4.5",
    discountpercentage: "40%",
    heading: "God of War Ragnarök (PC) -",
    subHeading: "STEAM Account - GLOBAL (05)",
    seller: "Sony Interactive",
    price: "8.00€",
    discountPrice: "5.00€",
  },
];

const specailUpcomingCardData = [
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: roblox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
  {
    bgImg: xbox,
    rating: "4.5",
    discountpercentage: "50%",
    heading: "ROBLOX Gift Cards",
    seller: "Giants Software",
    price: "20.00€",
    discountPrice: "10.00€",
  },
];

const ClientReviewCardData = [
  {
    clientImg: clientOne,
    clientName: "Adrian Sami",
    clientQuote:
      "I bought a gift card for my nephew’s birthday, and he absolutely loved it! He was so excited to pick out his own game and unlock new skins. It made the perfect gift for a gamer like him!”",
  },
  {
    clientImg: clientTwo,
    clientName: "James D",
    clientQuote:
      "I love how easy it is to buy a gift card and use it immediately. No need to worry about entering payment details every time I want to grab a new game. It's so convenient!",
  },
  {
    clientImg: clientTwo,
    clientName: "James D",
    clientQuote:
      "I love how easy it is to buy a gift card and use it immediately. No need to worry about entering payment details every time I want to grab a new game. It's so convenient!",
  },
  {
    clientImg: clientOne,
    clientName: "Adrian Sami",
    clientQuote:
      "I bought a gift card for my nephew’s birthday, and he absolutely loved it! He was so excited to pick out his own game and unlock new skins. It made the perfect gift for a gamer like him!”",
  },
];

export { giftCardData, bestsellingCardData , upcomingCardData , specailUpcomingCardData , ClientReviewCardData };
